apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        logz.io/skip: "true"
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
          name: apis-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
        - name: manager
          image: {{ .Values.manager.instrumentorImage }}:{{ .Values.manager.instrumentorTag }}
          env:
            - name: MONITORING_SERVICE_ENDPOINT
              value: {{ .Values.manager.monitoringServiceEndpoint }}
            - name: CURRENT_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: {{ .Values.manager.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.manager.livenessProbe.periodSeconds }}
          command:
            - /app
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
            - --instrumentation-detector-tag={{ .Values.manager.instrumentationDetectorTag }}
            - --instrumentation-detector-image={{ .Values.manager.instrumentationDetectorImage }}
          resources:
            limits:
              cpu: {{ .Values.manager.resources.limits.cpu }}
              memory: {{ .Values.manager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.manager.resources.requests.cpu }}
              memory: {{ .Values.manager.resources.requests.memory }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
