apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-instrumentor-leader-election
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logzio-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
