apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
      annotations:
        logz.io/instrument: "true"
    spec:
      containers:
        - env:
            - name: PORT
              value: "9555"
          image: edenfed/adservice:edae583@sha256:433d4beeeb38f96b915f887f7387305a5790895024fd33ecf976365760800c86
          name: server
          ports:
            - containerPort: 9555
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 180Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: default
spec:
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555
  selector:
    app: adservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        logz.io/instrument: "true"
    spec:
      containers:
        - env:
            - name: REDIS_ADDR
              value: redis-cart:6379
          image: edenfed/cartservice:edae583@sha256:07e850ee5884b37b82c1a550da42610519d907b836952eabf1aa4b4bb4f85b9e
          name: server
          ports:
            - containerPort: 7070
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 64Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: default
spec:
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070
  selector:
    app: cartservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
      annotations:
        logz.io/instrument: "true"
    spec:
      containers:
        - env:
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:3550
            - name: SHIPPING_SERVICE_ADDR
              value: shippingservice:50051
            - name: PAYMENT_SERVICE_ADDR
              value: paymentservice:50051
            - name: EMAIL_SERVICE_ADDR
              value: emailservice:5000
            - name: CURRENCY_SERVICE_ADDR
              value: currencyservice:7000
            - name: CART_SERVICE_ADDR
              value: cartservice:7070
          image: edenfed/checkoutservice:edae583@sha256:2d4ea6f4e2e1a19b252bf2369a36b993570a6fb5a9286ead25eda218ae49ccb4
          name: server
          ports:
            - containerPort: 5050
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: default
spec:
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050
  selector:
    app: checkoutservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
      annotations:
        logz.io/instrument: "true"
    spec:
      containers:
        - env:
            - name: PORT
              value: "7000"
          image: edenfed/currencyservice:edae583@sha256:80d3417dc01060335be0ebb5b79a9991b54b3fd792694a78588b0c744e2f73c8
          name: server
          ports:
            - containerPort: 7000
              name: grpc
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: default
spec:
  ports:
    - name: grpc
      port: 7000
      targetPort: 7000
  selector:
    app: currencyservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
      annotations:
        logz.io/instrument: "true"
    spec:
      containers:
        - env:
            - name: PORT
              value: "8080"
            - name: DISABLE_PROFILER
              value: "1"
          image: edenfed/emailservice:edae583@sha256:3f029a7f0d226419d092975c1a886e72e3c46e8ae1f1ddb0e966f65b61e082be
          name: server
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: default
spec:
  ports:
    - name: grpc
      port: 5000
      targetPort: 8080
  selector:
    app: emailservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        logz.io/instrument: "true"
      labels:
        app: frontend
    spec:
      containers:
        - env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:3550
            - name: CURRENCY_SERVICE_ADDR
              value: currencyservice:7000
            - name: CART_SERVICE_ADDR
              value: cartservice:7070
            - name: RECOMMENDATION_SERVICE_ADDR
              value: recommendationservice:8080
            - name: SHIPPING_SERVICE_ADDR
              value: shippingservice:50051
            - name: CHECKOUT_SERVICE_ADDR
              value: checkoutservice:5050
            - name: AD_SERVICE_ADDR
              value: adservice:9555
            - name: ENV_PLATFORM
              value: aws
          image: edenfed/frontend:edae583@sha256:ae2bfbc2675e3c1411b36ccc10906a2af722c29218f2bbad176063e908d099a8
          name: server
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  namespace: default
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8080
  selector:
    app: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
      annotations:
        logz.io/instrument: "true"
    spec:
      containers:
        - env:
            - name: PORT
              value: "50051"
          image: edenfed/paymentservice:edae583@sha256:28a857b161202840a4a98e4afa3444fd277c35eccfa7fea3b5e8eec88c87a44c
          name: server
          ports:
            - containerPort: 50051
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: default
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: paymentservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
      annotations:
        logz.io/instrument: "true"
    spec:
      containers:
        - env:
            - name: PORT
              value: "3550"
          image: edenfed/productcatalogservice:edae583@sha256:16f9c5537beb5dd70249e22ce378d817b9fd9a2eb0513d1374aa3dc1f5aef062
          name: server
          ports:
            - containerPort: 3550
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: default
spec:
  ports:
    - name: grpc
      port: 3550
      targetPort: 3550
  selector:
    app: productcatalogservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
      annotations:
        logz.io/instrument: "true"
    spec:
      containers:
        - env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:3550
          image: edenfed/recommendationservice:edae583@sha256:db56ed0c25aa2325bd0d78cb93ccf8cf66dff37962054c5c020d6f70256b8d43
          name: server
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 450Mi
            requests:
              cpu: 100m
              memory: 220Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: default
spec:
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
  selector:
    app: recommendationservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: default
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
      annotations:
        logz.io/instrument: "true"
    spec:
      containers:
        - image: redis:alpine
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          name: redis
          ports:
            - containerPort: 6379
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          resources:
            limits:
              cpu: 125m
              memory: 256Mi
            requests:
              cpu: 70m
              memory: 200Mi
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - emptyDir: {}
          name: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: default
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis-cart
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
      annotations:
        logz.io/instrument: "true"
    spec:
      containers:
        - env:
            - name: PORT
              value: "50051"
          image: edenfed/shippingservice:edae583@sha256:65ae7cd0d09a76cd6d60195a5fe03aaf538fb4f9bdcf77912d3c3f0fdaf75f9c
          name: server
          ports:
            - containerPort: 50051
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: default
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: shippingservice
  type: ClusterIP