apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ezkonnect-server
rules:
  - apiGroups:
      - ""
      - logz.io
      - apps
    resources:
      - pods
      - services
      - instrumentedapplications
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - update