apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logzio-kubernetes-manifests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logzio-kubernetes-manifests
subjects:
  - kind: ServiceAccount
    name: logzio-kubernetes-manifests
    namespace: default