apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezkonnect-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ezkonnect-server
  template:
    metadata:
      labels:
        app: ezkonnect-server
    spec:
      containers:
        - name: ezkonnect-server
          image: logzio/ezkonnect-server:v1.0.0
          ports:
            - containerPort: 5050
---
