apiVersion: v1
kind: Service
metadata:
  name: kubernetes-instrumentor-service
  namespace: default
spec:
  selector:
    app: kubernetes-instrumentor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
