apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logzio-instrumentor-leader-election
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logzio-leader-election-role
subjects:
- kind: ServiceAccount
  name: logzio-instrumentor
