name: Build and deploy instrumentor and detector image to dockerhub
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build images release
        run: TAG=${{ github.event.release.tag_name }} make build-images
      - name: Push images release
        run: TAG=${{ github.event.release.tag_name }} make push-images
      - name: Build images latest
        run: TAG=latest make build-images
      - name: Push images latest
        run: TAG=latest make push-images
      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build and push agent images to GitHub Packages
      - name: Build and push Docker images to GitHub Packages release
        run: |
          TAG=${{ github.event.release.tag_name }}
          # Dotnet Agent
          docker build -t ghcr.io/${{ github.repository }}/otel-agent-dotnet:$TAG -f agents/dotnet/Dockerfile agents/dotnet
          docker push ghcr.io/${{ github.repository }}/otel-agent-dotnet:$TAG          
          # Java Agent
          docker build -t ghcr.io/${{ github.repository }}/otel-agent-java:$TAG -f agents/java/Dockerfile agents/java
          docker push ghcr.io/${{ github.repository }}/otel-agent-java:$TAG
          # Node.js Agent
          docker build -t ghcr.io/${{ github.repository }}/otel-agent-nodejs:$TAG -f agents/nodejs/Dockerfile agents/nodejs
          docker push ghcr.io/${{ github.repository }}/otel-agent-nodejs:$TAG
          # Python Agent
          docker build -t ghcr.io/${{ github.repository }}/otel-agent-python:$TAG -f agents/python/Dockerfile agents/python
          docker push ghcr.io/${{ github.repository }}/otel-agent-python:$TAG
          # instrumentor
          docker build -t ghcr.io/${{ github.repository }}/instrumentation-detector:$TAG -f detectors/Dockerfile . --build-arg SERVICE_NAME=detectors
          docker push ghcr.io/${{ github.repository }}/instrumentation-detector:$TAG
          docker build -t ghcr.io/${{ github.repository }}/instrumentor:$TAG . --build-arg SERVICE_NAME=instrumentor
          docker push ghcr.io/${{ github.repository }}/instrumentor:$TAG

      # Build and push images to GitHub Packages
      - name: Build and push Docker images to GitHub Packages latest
        run: |
          TAG=latest
          # Dotnet Agent
          docker build -t ghcr.io/${{ github.repository }}/otel-agent-dotnet:$TAG -f agents/dotnet/Dockerfile agents/dotnet
          docker push ghcr.io/${{ github.repository }}/otel-agent-dotnet:$TAG
          # Java Agent
          docker build -t ghcr.io/${{ github.repository }}/otel-agent-java:$TAG -f agents/java/Dockerfile agents/java
          docker push ghcr.io/${{ github.repository }}/otel-agent-java:$TAG
          # Node.js Agent
          docker build -t ghcr.io/${{ github.repository }}/otel-agent-nodejs:$TAG -f agents/nodejs/Dockerfile agents/nodejs
          docker push ghcr.io/${{ github.repository }}/otel-agent-nodejs:$TAG
          # Python Agent
          docker build -t ghcr.io/${{ github.repository }}/otel-agent-python:$TAG -f agents/python/Dockerfile agents/python
          docker push ghcr.io/${{ github.repository }}/otel-agent-python:$TAG
          # instrumentor
          docker build -t ghcr.io/${{ github.repository }}/instrumentation-detector:$TAG -f detectors/Dockerfile . --build-arg SERVICE_NAME=detectors
          docker push ghcr.io/${{ github.repository }}/instrumentation-detector:$TAG
          docker build -t ghcr.io/${{ github.repository }}/instrumentor:$TAG . --build-arg SERVICE_NAME=instrumentor
          docker push ghcr.io/${{ github.repository }}/instrumentor:$TAG
