name: Build and deploy instrumentor and detector image to dockerhub
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build images release
        run: TAG=${{ github.event.release.tag_name }} make build-images
      - name: Push images release
        run: TAG=${{ github.event.release.tag_name }} make push-images
      - name: Build images latest
        run: TAG=latest make build-images
      - name: Push images latest
        run: TAG=latest make push-images
      # AWS ECR Public Login
      - name: Login to AWS ECR Public
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Build and push agent images to aws public ecr
      - name: Build and push Docker images to aws ecr release
        run: |
          TAG=${{ github.event.release.tag_name }}
          AWS_ECR_REGISTRY=public.ecr.aws/logzio
          # build
          docker build -t $AWS_ECR_REGISTRY/instrumentation-detector:$TAG -f detectors/Dockerfile . --build-arg SERVICE_NAME=detectors
          docker build -t $AWS_ECR_REGISTRY/instrumentor:$TAG . --build-arg SERVICE_NAME=instrumentor
          # push 
          docker push $AWS_ECR_REGISTRY/instrumentation-detector:$TAG
          docker push $AWS_ECR_REGISTRY/instrumentor:$TAG
      - name: Build and push Docker images to aws ecr release
        run: |
          TAG=latest
          AWS_ECR_REGISTRY=public.ecr.aws/your-ecr-registry-name
          # build
          docker build -t $AWS_ECR_REGISTRY/instrumentation-detector:$TAG -f detectors/Dockerfile . --build-arg SERVICE_NAME=detectors
          docker build -t $AWS_ECR_REGISTRY/instrumentor:$TAG . --build-arg SERVICE_NAME=instrumentor
          # push 
          docker push $AWS_ECR_REGISTRY/instrumentation-detector:$TAG
          docker push $AWS_ECR_REGISTRY/instrumentor:$TAG
